### PR TITLE
Support TLS

### PR DESCRIPTION
**Pull request by yosshy**
This patchset adds TLS connection capability. To make a TLS
connection, use tls:// schema for a NATS server. You can
specify additional options for NATSClient:

tls_cacert(str):      filepath for CA certificate(default:None)
tls_client_cert(str): filepath for a client certificate(default:None)
tls_client_key(str):  filepath for a client key(default:None)
tls_verify(bool):     Enable TLS verification(default:False)

### CODE REVIEW

**Comment by yosshy** [comment]
I'm sorry, I moved the branch from master to tls for the pull request.

**Comment by nineinchnick** [comment]
@yosshy looks like you deleted the original repo. I've copied your commit in my fork and rebased it against latest master: https://github.com/nineinchnick/nats-python/tree/tls

@Gr1N would that help in getting this accepted?

**Comment by Gr1N** [comment]
@nineinchnick hello, I will look into this during this week. Is it ok for you?

**Comment by nineinchnick** [comment]
Of course! No rush. I've noticed the pipelines failed and I'm updating tests to start NATS with TLS. I guess this warrants opening up a new PR, WDYT?

**Comment by Gr1N** [comment]
I guess I will take implementation into my own branch, apply some changes to the code, and configure CI to pass checks. And then I will open a new PR for review.

**Comment by nineinchnick** [comment]
That's exactly what I'm doing - I've opened #13 since I'm not sure that the pipeline runs for my branch without a PR.

EDIT: 🤦 yes it does, I just had a syntax error. Anyway, let's discuss there.

**Pull request closed without merging**
